name: Build and deploy Node.js app to Azure Web App - for-kev

on:
  push:
    branches:
      - test-deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'  # Adjust to your Node.js version

      - name: Install dependencies, build, and test
        working-directory: ./backend  # Set the working directory to your backend folder
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        working-directory: ./backend  # Set the working directory to your backend folder
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./backend/release.zip  # Adjust the path to your backend folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./backend  # Adjust the path to your backend folder

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'for-kev'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_733575E89E6142DFAB50FB1A47F2CFBE }}
          package: ./backend  # Adjust the path to your backend folder
